version: 2.1
commands:
  test:
    steps:
      - run: echo ok
jobs:
  base-images:
    docker:
      - image: circleci/node:4.8.2-jessie
    steps:
      - test
workflows:
  feature:
    jobs:
      - base-images
